title: How to use MicroK8s 
remote_theme: just-the-docs/just-the-docs
search_enabled: true
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: https://github.com/windperson/microk8s-setup-readme
